# Default budget thresholds for pipeline execution.
# Values can be overridden via environment variables (see config/budget_config.py).
defaults:
  max_http_requests: 500
  max_http_bytes: 10485760  # 10 MB
  time_budget_min: 0
  ram_mb: 0
