name: CI

on:
  push:
    branches:
      - "**"

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest mypy ruff

      - name: Run Ruff
        run: ruff check .

      - name: Run mypy
        run: mypy .

      - name: Run pytest
        run: pytest
